### ISSUE TITLE
/build/update-site is empty

### ISSUE THREAD

**Issue by smishy05** [xatkit-bot-platform/xatkit#22]
Hi,
I installed Xatkit on both Ubuntu 18.04.1 and Ubuntu 20.04, following the instructions given in the build. Now, I want to add the software to Eclipse. So, I went to. `Help > Install New Software > Add > Archive`. Then, I went to `$XATKIT_DEV/build/update-site` to add the archive. But, I did not find any file there. I faced this issue in both Ubuntu 18.04.1 and 20.04. 

Please kindly let me know if I need to provide more information.
Thanks in advance.

**Comment by hamzaed** [comment]
Hi,

Could you please run the script:
```
git submodule update --remote xatkit-eclipse
```
then run the build script again.

If you still run into this problem, could you please share your terminal output?

Thank you!
Hamza

Hamza

**Comment by smishy05** [comment]
Hi, 
Thanks a lot for the reply. I ran the command and my directory is still empty. Here is my terminal output:
`Submodule path 'xatkit-eclipse': checked out '851ee44589772c14d561572db9879476c8862d8b'`

Please let me know what I should do. 

Thanks,
Shailesh

**Comment by hamzaed** [comment]
You need to run the build script after updating the submodule:

```
./build.sh` --all --skip-tests --product
```

**Comment by smishy05** [comment]
I stored the output in the file output.txt
[output.txt](https://github.com/xatkit-bot-platform/xatkit/files/4711271/output.txt)
And in the terminal I got this:

```
Warning: default mime table not found: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/content-types.properties
Warning: default mime table not found: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/content-types.properties
warning(200): //home/shailesh/xatkit/xatkit-eclipse/languages/intent/com.xatkit.language.intent.parent/com.xatkit.language.intent/../com.xatkit.language.intent/src-gen/com/xatkit/language/intent/parser/antlr/internal/InternalIntent.g:465:2: Decision can match input such as "RULE_ID" using multiple alternatives: 1, 2
As a result, alternative(s) 2 were disabled for that input
warning(200): //home/shailesh/xatkit/xatkit-eclipse/languages/platform/com.xatkit.language.platform.parent/com.xatkit.language.platform/../com.xatkit.language.platform/src-gen/com/xatkit/language/platform/parser/antlr/internal/InternalPlatform.g:1096:2: Decision can match input such as "RULE_ID" using multiple alternatives: 1, 2
As a result, alternative(s) 2 were disabled for that input
cp: cannot stat 'runtime/target/xatkit-giphy-runtime*.jar': No such file or directory
unzip:  cannot find or open platform/target/xatkit-giphy-platform*.zip, platform/target/xatkit-giphy-platform*.zip.zip or platform/target/xatkit-giphy-platform*.zip.ZIP.

No zipfiles found.
cp: cannot stat 'runtime/target/xatkit-rest-runtime*.jar': No such file or directory
unzip:  cannot find or open platform/target/xatkit-rest-platform*.zip, platform/target/xatkit-rest-platform*.zip.zip or platform/target/xatkit-rest-platform*.zip.ZIP.

No zipfiles found.
cp: cannot stat 'runtime/target/xatkit-twitter-runtime*.jar': No such file or directory
unzip:  cannot find or open platform/target/xatkit-twitter-platform*.zip, platform/target/xatkit-twitter-platform*.zip.zip or platform/target/xatkit-twitter-platform*.zip.ZIP.

No zipfiles found.
```

**Comment by hamzaed** [comment]
From your log, it seems that the update site was successfully built. Check if you can find an archive called `com.xatkit.update-4.0.0-SNAPSHOT` at `xatkit\xatkit-eclipse\update\com.xatkit.update\target`. 
It's the same archive that you should find in the folder update-site but for some reasons it was not copied there. Use that archive to install the plugin.

We plan to provide an online update site to facilitate the installation process in the future.

Hamza

**Comment by smishy05** [comment]
I ran both the commands again. It worked! Thanks!

**Comment by hamzaed** [comment]
You're welcome! I'm glad it worked!
