### ISSUE TITLE
Build failure at Xatkit Metamodels Utility

### ISSUE THREAD

**Issue by samueldc** [xatkit-bot-platform/xatkit#30]
Here's the build output:

[INFO] --------------------< com.xatkit:metamodels-utils >---------------------
[INFO] Building Xatkit Metamodels Utility 3.0.0-SNAPSHOT                  [6/6]
[INFO] -------------------------------[ bundle ]-------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ metamodels-utils ---
[INFO] Deleting /opt/xatkit/xatkit-metamodels/metamodels-utils/target
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ metamodels-utils ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /opt/xatkit/xatkit-metamodels/metamodels-utils/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ metamodels-utils ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /opt/xatkit/xatkit-metamodels/metamodels-utils/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /opt/xatkit/xatkit-metamodels/metamodels-utils/src/main/java/com/xatkit/metamodels/utils/RuntimeModel.java:[3,25] package com.xatkit.intent does not exist
[ERROR] /opt/xatkit/xatkit-metamodels/metamodels-utils/src/main/java/com/xatkit/metamodels/utils/RuntimeModel.java:[4,25] package com.xatkit.intent does not exist
[ERROR] /opt/xatkit/xatkit-metamodels/metamodels-utils/src/main/java/com/xatkit/metamodels/utils/IntentWrapper.java:[3,25] package com.xatkit.intent does not exist
[ERROR] /opt/xatkit/xatkit-metamodels/metamodels-utils/src/main/java/com/xatkit/metamodels/utils/EventWrapper.java:[3,25] package com.xatkit.intent does not exist
[ERROR] /opt/xatkit/xatkit-metamodels/metamodels-utils/src/main/java/com/xatkit/metamodels/utils/EventWrapper.java:[4,25] package com.xatkit.intent does not exist
[ERROR] /opt/xatkit/xatkit-metamodels/metamodels-utils/src/main/java/com/xatkit/metamodels/utils/EventWrapper.java:[5,25] package com.xatkit.intent does not exist
[ERROR] /opt/xatkit/xatkit-metamodels/metamodels-utils/src/main/java/com/xatkit/metamodels/utils/RuntimeModel.java:[72,53] cannot find symbol
  symbol:   class EventInstance
  location: class com.xatkit.metamodels.utils.RuntimeModel
[ERROR] /opt/xatkit/xatkit-metamodels/metamodels-utils/src/main/java/com/xatkit/metamodels/utils/IntentWrapper.java:[7,26] cannot find symbol
  symbol:   class RecognizedIntent
  location: class com.xatkit.metamodels.utils.IntentWrapper
[ERROR] /opt/xatkit/xatkit-metamodels/metamodels-utils/src/main/java/com/xatkit/metamodels/utils/IntentWrapper.java:[11,12] cannot find symbol
  symbol:   class RecognizedIntent
  location: class com.xatkit.metamodels.utils.IntentWrapper
[ERROR] /opt/xatkit/xatkit-metamodels/metamodels-utils/src/main/java/com/xatkit/metamodels/utils/EventWrapper.java:[13,15] cannot find symbol
  symbol:   class EventInstance
  location: class com.xatkit.metamodels.utils.EventWrapper
[ERROR] /opt/xatkit/xatkit-metamodels/metamodels-utils/src/main/java/com/xatkit/metamodels/utils/EventWrapper.java:[15,25] cannot find symbol
  symbol:   class EventInstance
  location: class com.xatkit.metamodels.utils.EventWrapper
[ERROR] /opt/xatkit/xatkit-metamodels/metamodels-utils/src/main/java/com/xatkit/metamodels/utils/EventWrapper.java:[19,12] cannot find symbol
  symbol:   class EventInstance
  location: class com.xatkit.metamodels.utils.EventWrapper
[ERROR] /opt/xatkit/xatkit-metamodels/metamodels-utils/src/main/java/com/xatkit/metamodels/utils/RuntimeModel.java:[76,38] cannot find symbol
  symbol:   class RecognizedIntent
  location: class com.xatkit.metamodels.utils.RuntimeModel
[ERROR] /opt/xatkit/xatkit-metamodels/metamodels-utils/src/main/java/com/xatkit/metamodels/utils/RuntimeModel.java:[77,41] cannot find symbol
  symbol:   class RecognizedIntent
  location: class com.xatkit.metamodels.utils.RuntimeModel
[ERROR] /opt/xatkit/xatkit-metamodels/metamodels-utils/src/main/java/com/xatkit/metamodels/utils/EventWrapper.java:[29,13] cannot find symbol
  symbol:   class ContextInstance
  location: class com.xatkit.metamodels.utils.EventWrapper
[ERROR] /opt/xatkit/xatkit-metamodels/metamodels-utils/src/main/java/com/xatkit/metamodels/utils/EventWrapper.java:[34,17] cannot find symbol
  symbol:   class ContextParameterValue
  location: class com.xatkit.metamodels.utils.EventWrapper
[ERROR] /opt/xatkit/xatkit-metamodels/metamodels-utils/src/main/java/com/xatkit/metamodels/utils/IntentWrapper.java:[12,17] cannot find symbol
  symbol:   class RecognizedIntent
  location: class com.xatkit.metamodels.utils.IntentWrapper
[INFO] 17 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Xatkit Metamodels 3.0.0-SNAPSHOT:
[INFO] 
[INFO] Xatkit Metamodels .................................. SUCCESS [  1.081 s]
[INFO] Xatkit common model ................................ SUCCESS [ 13.761 s]
[INFO] Xatkit intent model ................................ SUCCESS [ 11.893 s]
[INFO] Xatkit platform model .............................. SUCCESS [  8.539 s]
[INFO] Xatkit execution model ............................. SUCCESS [  5.744 s]
[INFO] Xatkit Metamodels Utility .......................... FAILURE [  1.143 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  43.902 s
[INFO] Finished at: 2020-07-09T17:31:44-03:00
[INFO] ------------------------------------------------------------------------

**Comment by samueldc** [comment]
When I try to run, here's the output:

Xatkit classpath:
/opt/xatkit/build/examples/community/Twitter/CanYouTweet/lib/xatkit-twitter-runtime-1.0.1-SNAPSHOT.jar
/opt/xatkit/build/examples/WeatherBot/lib/xatkit-rest-runtime-2.0.0-SNAPSHOT.jar
/opt/xatkit/build/examples/GitHubBots/GithubBot/lib/xatkit-github-runtime-2.1.1-SNAPSHOT.jar
java -Dfile.encoding=UTF-8 -cp '/opt/xatkit/build/examples/community/Twitter/CanYouTweet/lib/xatkit-twitter-runtime-1.0.1-SNAPSHOT.jar:/opt/xatkit/build/examples/WeatherBot/lib/xatkit-rest-runtime-2.0.0-SNAPSHOT.jar:/opt/xatkit/build/examples/GitHubBots/GithubBot/lib/xatkit-github-runtime-2.1.1-SNAPSHOT.jar' com.xatkit.Xatkit '../examples/GreetingsBots/GreetingsBot/GreetingsBot.properties'
Error: Could not find or load main class com.xatkit.Xatkit

**Comment by ysong10** [comment]
hi. I have the same problem when building metamodels.  Do you know how to solve it? Thanks

**Comment by gdaniel** [comment]
Hi @samueldc, @ysong10, @hamzaed found the origin of your issue and has created a pull request to fix it. I'll let you know when it's merged and give you the instructions to update.

**Comment by gdaniel** [comment]
The metamodel build should work fine now, let me know if you have an issue 🙂

**Comment by samueldc** [comment]
Hi @gdaniel. Everything looks fine now. Thanks.
