### ISSUE TITLE
running the GreetingsBot

### ISSUE THREAD

**Issue by lburgueno** [xatkit-bot-platform/xatkit#36]
There is a typo in the instructions to run the GreetingsBot, it should be:
cd xatkit-examples/GreetingsBots/GreetingsBot instead of
cd xatkit-examples/GreetingsBot/GreetingsBot
(only a missing -s in the folder name)

**Comment by gdaniel** [comment]
Hi Loli,
Could you give me the link of the page with the typo? I looked at the README/Wiki but couldn't find it.

**Comment by lburgueno** [comment]
Sure! This one: https://github.com/xatkit-bot-platform/xatkit/wiki/Build-Xatkit

**Comment by gdaniel** [comment]
Thanks! It was hidden in the TL;DR 😄 
I just fixed it!
